version: 0.2
env:
  variables:
    REACT_APP_DEMO_VAR: 'demo'
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - export npm_config_cache=/tmp/cache/
      - npm i--legacy-peer-deps
  build:
    commands:
      - echo Building
      - npm run build
      - la -la
      - echo Done
 # post_build:
 #   commands:
#      - mv build/* ./
#      - rm -R build-output *.yml LICENSE README* .git*
artifacts:
  files:
    - '**/*'
    - 'build/**/*'
  discard-paths: no
  base-directory: 'build'
