version: 0.2
env:
  variables:
    REACT_APP_DEMO_VAR: 'demo'
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install yarn
      - yarn
      - yarn add eslint-config-react-app
  build:
    commands:
      - echo Building
      - yarn build
 # post_build:
 #   commands:
#      - mv build/* ./
#      - rm -R build-output *.yml LICENSE README* .git*
artifacts:
  files:
    - '**/*'
    - 'build/**/*'
  base-directory: 'build'
